bitcoindevkit/bdk_wallet

wallet/Cargo.toml

This PR removes `lazy_static` from `Cargo.toml`. Apparently it wasn't being imported anywhere.

chore: remove `lazy_static` from Cargo.toml

---

examples/example_wallet_esplora_async/Cargo.toml

This PR bumps `tokio` to 1.38.1 on `example_wallet_esplora_async` due to a security vulnerability.

chore(example_wallet_esplora_async): bump tokio to 1.38.1

---

ci/pin-msrv.sh
examples/example_wallet_electrum/Cargo.toml
examples/example_wallet_electrum/src/main.rs
examples/example_wallet_esplora_async/Cargo.toml
examples/example_wallet_esplora_blocking/Cargo.toml
examples/example_wallet_esplora_blocking/src/main.rs
examples/example_wallet_rpc/Cargo.toml
examples/example_wallet_rpc/src/main.rs
wallet/Cargo.toml
wallet/README.md
wallet/src/test_utils.rs
wallet/src/wallet/mod.rs
wallet/src/wallet/persisted.rs
wallet/tests/wallet.rs

This PR updates `bdk_chain` dependency to the latest version 0.22.0
This PR doesn't make use of `CanonicalizationParams` for any advanced use cases - instead we rely on the default params for all tx-graph queries.
fixes #202
fixes #224
- deps: bump `bdk_chain` to 0.22.0
- deps: bump `bdk_file_store` to 0.20.0
- Added `start_sync_with_revealed_spks_at`
- Added `start_full_scan_at`
- Added `apply_evicted_txs`
- `start_sync_with_revealed_spks` is feature gated by "std", as it uses the system time to provide the time of the sync and also the tx last-seen.
- `apply_update` no longer requires std, as the timestamp is provided in the sync / full scan request
- `start_full_scan` is also gated behind "std"
- `start_sync_*` now includes the expected SPK history (via `list_expected_spk_txids`)
- …

deps!: update `bdk_chain` to 0.22.0

---

wallet/Cargo.toml

This PR implements the discussion started on #19, as well as discussions over a few dev calls.
The preferred approach is the one used by [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/Cargo.toml).
The core workflow for this is to keep the version on the master branch always an `alpha.0`, and simply update it to the next planned release once a branch has been created for a release.
So for example, the master branch could be on `1.3.0-alpha.0` until the branch for 1.3.0 is cut, at which moment the master moves on to `1.4.0-alpha.0`. Someone pulling the master branch is always building one of those `-alpha.0` versions.
None.

Chore: migrate library version naming convention on master

---

wallet/src/wallet/changeset.rs
wallet/src/wallet/mod.rs

This work in progress PR is meant to expand on and clarify the documentation for `bdk_wallet::ChangeSet`.
fixes #9
TBD

docs(wallet): provide guidance on use of `ChangeSet`

---

.github/workflows/cont_integration.yml

This PR adds Ubuntu 24.04 ARM as a target platform for the build-test job in our CI workflow. This change will help ensure our codebase works correctly on ARM architecture.
- Added `ubuntu-24.04-arm` to the matrix of operating systems in the build-test job
- Modified `runs-on` to use the matrix variable for OS selection
- Maintained existing test configurations (Rust versions and features)
The CI workflow will now run in parallel on both:
- Ubuntu latest (x86_64)
- Ubuntu 24.04 ARM
Each platform will test all combinations of:
- Rust versions (latest and MSRV 1.63.0)
- Feature combinations (no-std and all-features)
- Ensures compatibility with ARM-based systems
- Expands test coverage to include ARM architecture
- Helps catch potential architecture-specific issues early
Issue: …

ci: Add Ubuntu 24.04 ARM support for build-test job

---

.github/workflows/code_coverage.yml
.github/workflows/cont_integration.yml
.github/workflows/cron-update-rust.yml
.github/workflows/zizmor.yml
wallet/src/wallet/signer.rs
wallet/tests/psbt.rs

Added workflow to run zizmor github actions security analysis. 
See: https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
Original PR: https://github.com/bitcoindevkit/bdk/pull/1813
I pinned zizmor to version 1.6.0.
* ci: add zizmor github actions security analysis workflow and fix possible vulnerabilities

Add zizmor github actions security analysis workflow

---

.github/pull_request_template.md
.github/workflows/cont_integration.yml
rustfmt.toml
wallet/examples/compiler.rs
wallet/examples/policy.rs
wallet/src/descriptor/checksum.rs
wallet/src/descriptor/dsl.rs
wallet/src/descriptor/mod.rs
wallet/src/descriptor/policy.rs
wallet/src/descriptor/template.rs
wallet/src/keys/mod.rs
wallet/src/psbt/mod.rs
wallet/src/types.rs
wallet/src/wallet/changeset.rs
wallet/src/wallet/coin_selection.rs
wallet/src/wallet/mod.rs
wallet/src/wallet/persisted.rs
wallet/src/wallet/signer.rs
wallet/src/wallet/tx_builder.rs
wallet/tests/wallet.rs

Closes #3.
This PR adds basic formatting configuration for uniform comments. Note that the nightly toolchain is necessary.
Changes:
- Add `rustfmt.toml` with this config:
```
comment_width = 100
format_code_in_doc_comments = true
wrap_comments = true
```
- Apply `rustfmt.toml`.
- Update the `fmt` CI job to use the nightly toolchain.
- Update PR template to use nightly toolchain (`cargo fmt` -> `cargo +nightly fmt`).
Note: I had to add `#[rustfmt::skip]` to `test_extract_satisfaction_timelock()` because the base64 PSBT would get wrapped due to the slashes.

chore: create and apply rustfmt.toml

---

wallet/src/test_utils.rs
wallet/tests/wallet.rs

This PR closes #134 and is a revival of https://github.com/bitcoindevkit/bdk/pull/1130, which adds the following tests:
- `test_legacy_bump_fee_no_change_add_input_and_change()`
- `test_legacy_bump_fee_add_input()`
- `test_legacy_bump_fee_drain_wallet()`
- `test_legacy_bump_fee_zero_abs()`
- `test_legacy_create_tx_custom_sighash()`
- `test_legacy_create_tx_default_sighash()`
- `test_legacy_create_tx_absolute_high_fee()`
- `test_legacy_create_tx_absolute_zero_fee()`
- `test_legacy_create_tx_absolute_fee()`
- `test_legacy_create_tx_custom_fee_rate()`
- `test_legacy_get_funded_wallet_tx_fee_rate()`
- Add the above mentioned tests.
- Add a new `assert_fee_rate_legacy!` macro for legacy transactions.
- The `check_fee!` macro now returns `Amount` instead of `Result<Amount>`.
- All …

feat(test): add legacy descriptor tests

---

wallet/src/test_utils.rs
wallet/src/wallet/export.rs
wallet/src/wallet/tx_builder.rs
wallet/tests/wallet.rs

This PR simply updates tests to use `bitcoin::Amount` instead of `u64`.

feat(test-utils)!: use `bitcoin::Amount` instead of `u64` on tests

---

wallet/src/wallet/error.rs
wallet/src/wallet/mod.rs

Fixes #50
Fixes #51
Replaces bitcoindevkit/bdk#1911
Replaces bitcoindevkit/bdk#1913
We should check the bounds of the prev txs.
```md
Fixed:
- Wallet::get_psbt_input method now checks bounds when fetching prevout
- Wallet::build_fee_bump method now checks bounds when fetching prevout
```
~~* [ ] I've added tests to reproduce the issue which are now passing~~

fix: Validate prevouts in `get_psbt_input`

---

wallet/src/wallet/mod.rs
wallet/src/wallet/utils.rs
wallet/tests/wallet.rs

Fixes #100.
The `TxDetails` feature was put aside to focus on the 1.0 release, but now that we're done with that I want to revive the idea.
This is very much WIP. I'm trying to figure out exactly what we want in this data structure, and I'm not even sure my way to get at the data is the most efficient way to do it.
```md
Added:
- Wallet::get_tx_details method [#201]
[#201]: https://github.com/bitcoindevkit/bdk_wallet/pull/201
```

Bring back TxDetails

---

examples/example_wallet_electrum/Cargo.toml
examples/example_wallet_esplora_async/Cargo.toml
examples/example_wallet_esplora_blocking/Cargo.toml
examples/example_wallet_rpc/Cargo.toml
wallet/Cargo.toml
wallet/src/wallet/coin_selection.rs
wallet/src/wallet/mod.rs
wallet/src/wallet/params.rs
wallet/src/wallet/tx_builder.rs
wallet/tests/wallet.rs

The PR updates bdk_chain to 0.23.0. Additionally we introduce the ability to persist derived SPKs indexed by descriptor ID and derivation index.
The `CreateParams::use_spk_cache` method enables or disables a persistent cache for script pubkeys (SPKs) derived by the wallet. When enabled, the wallet will store and reuse previously derived SPKs, avoiding redundant derivation on subsequent loads.
When a wallet has many revealed addresses (i.e., many derived SPKs), loading the wallet can become slow if every address must be re-derived from scratch.
By enabling the SPK cache:
- **On wallet creation:** The wallet will persistently store each derived SPK as addresses are revealed.
- **On wallet load:** If `use_spk_cache` is also set in the corresponding `LoadParams`, the wallet will load the …

deps: Update `bdk_chain` to 0.23.0

---

wallet/CHANGELOG.md
wallet/Cargo.toml

Release crate version 2.0.0-beta.0 and update `CHANGELOG.md`.

Release 2.0.0-beta.0

---

wallet/Cargo.toml

Starting with commit `f6fd9853e`, `bdk_wallet` makes use of `bitcoin::key::TweakedKeyPair::to_keypair` which was introduced with v0.32.6. Here, we adjust the minimum API requirement in `Cargo.toml`, as BDK 2.0.0 builds could otherwise fail with:
```
error[E0599]: no method named `to_keypair` found for struct `TweakedKeypair` in the current scope
--> /home/tnull/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bdk_wallet-2.0.0/src/wallet/signer.rs:580:14
|
578 |           None => keypair
|  _________________-
579 | |             .tap_tweak(secp, psbt_input.tap_merkle_root)
580 | |             .to_keypair(),
| |             -^^^^^^^^^^ method not found in `TweakedKeypair`
| |_____________|
|
For more information about this error, try `rustc --explain E0599`.
```

Bump `bitcoin` dependency requirement to v0.32.6 to reflect used API

---

.github/pull_request_template.md
README.md
justfile

Closes #240.
This PR adds a `justfile`, updates the PR template to use it, and adds a section on the `README.md` to show available recipes.
These are the implemented recipes:
```justfile
alias b := build
alias c := check
alias f := fmt
alias t := test
alias p := pre-push
build:
cargo build
check:
cargo +nightly fmt --all -- --check
cargo check --workspace --exclude 'example_*' --all-features
cargo clippy --all-features --all-targets -- -D warnings
@[ "$(git log --pretty='format:%G?' -1 HEAD)" = "N" ] && \
echo "\n⚠️  Unsigned commit: BDK requires that commits be signed." || \
true
fmt:
cargo +nightly fmt
test:
cargo test --workspace --exclude 'example_*' --all-features
pre-push: fmt check test
```
`check` will verify if `HEAD` was signed and echo that warning if not. It does not check all …

feat: add `justfile`

---

wallet/src/wallet/coin_selection.rs

The comments in the `OldestFirstCoinSelection` implementation stated the following:
> // For utxo that doesn't exist in DB, they will have lowest priority to be selected
But this was not honored in the code.
This PR enforces this and ensures the expected behaviour through the two following new tests:
- `test_oldest_first_coin_selection_uses_all_optional_with_foreign_utxo_locals_sorted_first`
- `test_oldest_first_coin_selection_uses_only_all_optional_local_utxos_not_a_single_foreign`
Fixes #264 
No public APIs are changed by these commits.
> [!IMPORTANT]
> This pull request **DOES NOT** break the existing API

Prefer Utxo::Local over Utxo::Foreign in OldestFirstCoinSelection

---

wallet/src/wallet/mod.rs
wallet/src/wallet/tx_builder.rs
wallet/tests/wallet.rs

On my attempt to fix bitcoindevkit/bdk#1794 in bitcoindevkit/bdk#1798, I broke the assumption that insertion order is preserved when `TxBuilder::ordering` is `TxOrdering::Untouched`. Some users are relying in this assumption, so here I'm trying to restore it back, without adding a new dependency for this single use case like #252, or creating a new struct just to track this.
In this fourth alternative solution I'm going back to use `Vec` to store the manually selected UTxOs.
I was reluctant to do it in this way because `HashMap` seems a better solution giving its property of avoiding duplicates, but as we also want to keep the secuential nature of the insertion of UTxOs in `TxBuilder`, here is an alternative aligned with that principle. 
May replace #252 
May replace #261 .
Fixes #244 …

Preserve insertion order of manually selected utxos if `TxOrdering::Untouched`

---

wallet/src/wallet/tx_builder.rs

Fixes #143
These are convenience methods on `TxBuilder` that can be used to filter out outpoints which do not meet a given confirmation threshold.
Previously, I advocated a feature freeze on `TxBuilder`, but I believe we can make an exception for these helper methods, as they do not broaden the `TxBuilder` interface’s error surface. Going forward, all other development should be directed to the [`bdk-tx`](https://github.com/bitcoindevkit/bdk-tx) repository and crate.
cc. @tnull 
```md
Added:
- `TxBuilder::exclude_unconfirmed`
- `TxBuilder::exclude_below_confirmations`
```

feat: Add `exclude_unconfirmed` and `exclude_below_confirmations`

---

clippy.toml
wallet/src/wallet/mod.rs
wallet/src/wallet/persisted.rs
wallet/tests/persisted_wallet.rs

Reverts bitcoindevkit/bdk_wallet#277
Per discussion on team chat yesterday we need to revert this since it's a breaking change and wasn't meant to be merged until the 3.0 milestone. ValuedMammal will have to re-submit a replacement PR.

Revert "clippy!: `Box` large enum variants"

---

wallet/src/descriptor/error.rs
wallet/src/descriptor/mod.rs
wallet/src/wallet/mod.rs
wallet/src/wallet/params.rs

- New API: `Wallet::create_multipath(descriptor)` following the same pattern as `create()` and `create_single()`
- [BIP 389](https://github.com/bitcoin/bips/blob/master/bip-0389.mediawiki) compliance with exactly 2-path validation (receive and change)
- Robust validation with clear error messages
- Pattern consistency with existing wallet creation methods
```rust
let multipath_desc = "wpkh([9a6a2580/84'/1'/0']tpub.../‹0;1›/*)";
let wallet = Wallet::create_multipath(multipath_desc)
.network(Network::Testnet)
.create_wallet_no_persist()?;
// Automatically creates separate receive and change descriptors
let receive_addr = wallet.peek_address(KeychainKind::External, 0);  // Uses path /0/*
let change_addr = wallet.peek_address(KeychainKind::Internal, 0);   // Uses path /1/*
```
1. Pattern …

Multipath descriptor support (BIP 389)

---

wallet/src/wallet/mod.rs
wallet/tests/persisted_wallet.rs

We should ensure we populate the cache (from the changeset) before doing any other operation on `KeychainTxOutIndex` (i.e. inserting descriptors).
Otherwise we will end up re-deriving spks which have already been cached.
The test is also corrected to check that we don't duplicate deriving spks. A helper function `check_cache_cs` is added to make the tests more thorough and easier to read.
```md
Fixed:
* Recovering from spk-cache now works properly.
```
> ~* [ ] This pull request breaks the existing API~
> ~* [ ] I'm linking the issue being fixed by this PR~

Fix `KeychainTxOutIndex` recovery logic when spk-cache is enabled

---

examples/example_wallet_electrum/Cargo.toml
examples/example_wallet_esplora_async/Cargo.toml
examples/example_wallet_esplora_blocking/Cargo.toml
examples/example_wallet_rpc/Cargo.toml
examples/example_wallet_rpc/src/main.rs
wallet/Cargo.toml
wallet/tests/wallet.rs

- updates the `bdk-chain` to `0.23.1` in `bdk_wallet`.
- updates the `esplora`, `electrum` and `bitcoind_rpc` to latest version.
I had to update the `insert_tx` in `test_utils` and the `wallet_rpc` example in order to work with bumped versions, let me know if all sounds good.
```md
- deps: bump `bdk-chain` to `0.23.1`
```

chore(deps): bump `bdk-chain` to `0.23.1`

---

wallet/CHANGELOG.md
wallet/Cargo.toml

fixes #286 ; depends on #292 
- updates the version to `2.1.0`
- updates the `CHANGELOG.md`
```md
- update the bdk_wallet version to `2.1.0`
```

Release 2.1.0

---

.github/workflows/code_coverage.yml
.github/workflows/cont_integration.yml

Bump Swatinem/rust-cache to v2.8.0.
`Swatinem/rust-cache` is now pinned to a commit at [98c8021b550208e191a6a3145459bfc9fb29c4c0](https://github.com/Swatinem/rust-cache/commit/98c8021b550208e191a6a3145459bfc9fb29c4c0).
ci: bump rust-cache to 2.8.0

ci: bump rust-cache to 2.8.0

---

wallet/src/wallet/mod.rs

This PR makes explicit a limitation of the `Wallet::create_from_two_path_descriptor` method, in that you must use public descriptors to build the wallet using this constructor, meaning you can only build watch-only wallets.
I also added a test to showcase this and the error returned.
See [my comment here](https://github.com/bitcoindevkit/bdk_wallet/pull/275#issuecomment-3251334629) for more:
From what I can tell the issue is that miniscript cannot parse an xprv (I saw a comment from Sanket about this somewhere but now I can't find it anymore) if the multipath contains hardened derivation paths, and therefore miniscipt cannot ensure the xprv will be parsable into public keys in all cases? Something like that. But our arguments for bdk wallet constructors require the `IntoWalletDescriptor` …

Add docs + test on required use of xpub for multipath constructor

---

wallet/Cargo.toml

PR updates the master dev version to 3.0.0-alpha.0.
fix #304

chore: bump dev version to 3.0.0-alpha.0

---

examples/example_wallet_electrum/src/main.rs
examples/example_wallet_esplora_async/src/main.rs
examples/example_wallet_esplora_blocking/src/main.rs
wallet/CHANGELOG.md
wallet/Cargo.toml
wallet/examples/policy.rs
wallet/src/lib.rs
wallet/src/wallet/mod.rs
wallet/tests/add_foreign_utxo.rs
wallet/tests/persisted_wallet.rs
wallet/tests/psbt.rs
wallet/tests/wallet.rs
wallet/tests/wallet_event.rs

Bump `bdk_wallet` to 2.2.0 and update `CHANGELOG.md`. Note that `signer` module is now deprecated and planned to be removed in an upcoming release. Current PSBT signing logic now lives in [`bitcoin::psbt`](https://docs.rs/bitcoin/latest/bitcoin/psbt/index.html) module.
fix #307

Release v2.2.0
